### PR TITLE
added french translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by xingrz** [comment]
Thank you very much!

I'll review and merge it as soon as possible.

**Comment by ghost** [comment]
You're welcome and thanks to you for this beautiful live wallpaper!

**Comment by xingrz** [comment]
Hi @M2ck , sorry I'm late. I just cleaned up and pushed the latest code. Would you please update the translation?

**Comment by ghost** [comment]
Hi @xingrz, don't worry, better late than never :)

Done! I've improved a few old strings and updated the new ones.

**Comment by xingrz** [comment]
Great!

Would you please rebase your patch to the latest `master` base?

``` sh
git checkout patch-1
git remote add upstream https://github.com/oxoooo/earth.git
git pull --rebase upstream master
git push origin patch-1 -f
```

**Comment by ghost** [comment]
Sorry I'm using GitHub only via my browser for translation I'm not developer at all.

How proceed? Close this PR and open a new one could be a good workaround for you?

Sorry again, I'm feel dumb...^^'

**Comment by xingrz** [comment]
Don't worry @M2ck . Instead I can do this for you. But in that way this PR will not turn `Merged` but `Closed`. It's a general way.

**Comment by xingrz** [comment]
Done. Rebased as a7c869f6474dc79450f1d344c9eef993a4730b66 and merged.

**Comment by ghost** [comment]
Perfect, thanks!

**Pull request closed without merging**
